### ISSUE TITLE
FIGMA celular pagina inicial

### ISSUE THREAD

**Issue by Enildo5** [senacgo-hugotannus/nutri-calc-frontend#48]
Criação da página principal via celular utilizando FIGMA, com Histórico de IMC, TMB, GE no topo da página e criando a barra de menu no down da página.

[ Criação de um container, contendo o histórico do usuário.] "Sugestão"

**Comment by zGuxta** [comment]
![WhatsApp Image 2024-10-15 at 11 24 41](https://github.com/user-attachments/assets/0c6b1637-a6b6-45ca-b7f7-bafb54fa303d)
WireFrame Mobile
