### ISSUE TITLE
FIGMA celular pagina calculo

### ISSUE THREAD

**Issue by Enildo5** [senacgo-hugotannus/nutri-calc-frontend#49]
Criação da página de cálculo via celular utilizando FIGMA, com Histórico de IMC, TMB, GE no topo da página e reutilizando a barra de menu no down da página.

No meio da página utilizar um container com a calculadora.

**Comment by zGuxta** [comment]
Prototipação feita na issue https://github.com/senacgo-hugotannus/nutri-calc-frontend/issues/48
