### ISSUE TITLE
FIGMA desktop pagina inicial

### ISSUE THREAD

**Issue by Enildo5** [senacgo-hugotannus/nutri-calc-frontend#52]
Criação da página inicial via desktop utilizando FIGMA, com Histórico de IMC, TMB, GE no rodapé  da página e criando a barra de menu no nav-bar da página, contendo Home, Calculo, Dieta, Histórico.

[ Criar um container contendo um input de pesquisa, informações do site ] "Sugestão"  "Deixar o histórico no rodapé da página com o último histórico do usuário. Caso não exista nenhum histórico mostrar zerado"

**Comment by RicardoLAP** [comment]
https://www.figma.com/design/8cDufXIbDRlOXdBI3ZY6e0/Untitled?node-id=0-1&m=dev&t=KlMvd3dtX9lEADPm-1
