### ISSUE TITLE
FIGMA celular pagina histórico

### ISSUE THREAD

**Issue by Enildo5** [senacgo-hugotannus/nutri-calc-frontend#68]
Criação da página de histórico via celular utilizando FIGMA, com Histórico de IMC, TMB, GE no topo da página e reutilizando a barra de menu no down da página.

No meio da página conter o última Histórico do usuário [ "Sugestão"]

**Comment by zGuxta** [comment]
Prototipação na issue https://github.com/senacgo-hugotannus/nutri-calc-frontend/issues/48
